sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-555.pdf --upload --lsstdoc LDM-555.tex --env=travis --ltd-product ldm-555"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "i6QTPCGNwp9v9BaQX8OUkglEIc5xfil27WziH/4PnyZW1z6z98sFNri6j2AdhY/4pu5WTNzkT5gCamxY2VXTYkNJ2CAsI/5a1YQmcQ45i80B3YjqPfYcwc34Z/2deRXoXwQfIzhMbGB3agA/BqOKg6KxfiByit/yTwP9Ea622qIYyQhxoHAf+7UvMMopLhpQ0IWvOZqokhRy9X+3ZQxGiFq09sZIy8Pl6AKf5AeOh+FbJji71DhV/eeIE7TyJ+TMmUlvlbhIwYCuGJMlqmgbvmVkY/JEKjwFURh0PEoKSDLq/UmxL+XSRQQwPKl7k3go7xR5VoETbQSBCLU+a1T8axKATC1xZqe/Z3yOn0jZD3vzEwKdXpiLH2fWBuiA5Fr0lMP++O35NYLAMw7YUhnUm+IFf5NU1Rk/4Mz3hclVWzyf2Y9R9/X4BCmFxDktV9sfN+KBSmBaqcwyYxEX9AaljDr5r8CnyMH+qFpFwjx/CDmxg1xSePQNRhuKKAq0WMnRp/o/8dmq4vTTZMM4fjwiykUlNVb5MkycZBJ3YprQpAlKXH7fcgg+XsPsGwGHR698LKpHvYSjkoJrqvIkXJ+cZ7vDnaSoaKyeGzvY57SsavI3UFsGN6W6L2bniDswbByOncN7tAaff7k3vuhnNapjdod5i9BG+CSrqAY0I9fld2A="
    - secure: "RWF44fqIVVn0dTEXFsSIGLJLJCW9zR9ZnYsFgfVRMIPOX7TB/VH5xkY6MtxvZ5VizkD549aH4AoHKluRqUuUW+6ftCjtsM5GLCmQNV5cCy1bTHKvVxWBFxJVFKSXVQETHWYS+VFz+Mqw9NRWhURUmsfg0k4JoGxpHDPozlC0qo0FnGw/qM8FWpJul3PXN+orqg32URPEs+qwojuU2Nvr55CuF9VgWB+v5djN8DfWE1oFBbUxMf1y4opRUMCS4bwKJZ5NxlQqSELl4uqegjNjj6YitIR9PgMSx7cU3MSYMEsHl1Bf+xi1WORfOeOqsdueel3q1K8cWFLy5XDOyN5vkbOIFPBffwn4XOEW3FT/v/n4WOYa3h0msoZ5xbq7bq9T/H8dPwgOCbEMOs01NK6SWLu4wKhu/afng7IQoX2K+ekfi7OHydKxfmikjrBSovMsB9avB7mbIAauOmdA+eL5gKbOe9ngSkxm4VKhG36Bq51PbqWE73msAkVwLepk3yDcGAdMFwcny0LA3gkzDpjtKbPrNwH3IiM8Saf+MaM0rOKQqKKTd7Dz1pGbfYGoD1kbq00f4XNezd3Q0bHxXGa2beHjcnxsP4oupEo+YmBbRHkOpca8wi7oo3asqGQeqUTsCrmAMAmBkNxZvAhDBRDHKuOYQuL17ekMt7S1cd9GfRo="
